### ISSUE TITLE
Not working for Mac M1

### ISSUE THREAD

**Issue by s-weissbach** [divieira/sonpy#1]
Hey,
tried to import sonpy on a Mac M1 with
`import sonpy`,
which led to the error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sonpy/__init__.py", line 10, in <module>
    import sonpy.darwin.sonpy as lib
ImportError: dlopen(/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sonpy/darwin/sonpy.so, 0x0002): tried: '/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sonpy/darwin/sonpy.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```
Will M1 support be added?

**Comment by divieira** [comment]
Hi,

Sorry for the delay in replying. This repository in only a public mirror to the legacy sonpy code, which to my knowledge is no longer maintained.

I would suggest looking into the neo package, which supports reading from .smr files and is currently maintained (see https://neo.readthedocs.io/en/stable/examples.html for an example on using the neo.io.Spike2IO class).

**Comment by s-weissbach** [comment]
This is very unfortunate. The neo library imports sonpy, so the suggested solution is not working.
https://github.com/NeuralEnsemble/python-neo/blob/master/neo/rawio/cedrawio.py 
at line 51
```PYTHON    
def _parse_header(self):
        import sonpy

        self.smrx_file = sonpy.lib.SonFile(sName=str(self.filename), bReadOnly=True)
```

**Comment by divieira** [comment]
I have been using neo on a M1 Macbook Pro to open .smr files without a problem.

Looking at your original comment, I have noticed you seem to be using conda miniforge. I would suggest trying to install the packages directly with pip (as I am doing), preferably in a new Python virtual environment or installation.

For sonpy, you can then install it directly from Github using pip:
> pip install git+https://github.com/divieira/sonpy.git
